package amilalaflower.mbg.entity;

public class EMachineDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_MACHINE_DATA.ERROR_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    private Integer errorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_MACHINE_DATA.ERROR_ID
     *
     * @return the value of E_MACHINE_DATA.ERROR_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public Integer getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_MACHINE_DATA.ERROR_ID
     *
     * @param errorId the value for E_MACHINE_DATA.ERROR_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public void setErrorId(Integer errorId) {
        this.errorId = errorId;
    }
}