package amilalaflower.mbg.entity;

public class MHallInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_HALL_INFO.HALL_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    private String hallId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_HALL_INFO.HALL_ID
     *
     * @return the value of M_HALL_INFO.HALL_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public String getHallId() {
        return hallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_HALL_INFO.HALL_ID
     *
     * @param hallId the value for M_HALL_INFO.HALL_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }
}