package amilalaflower.mbg.entity;

public class MMachineList extends MMachineListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MACHINE_LIST.PS_FLG
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    private String psFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MACHINE_LIST.PS_FLG
     *
     * @return the value of M_MACHINE_LIST.PS_FLG
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public String getPsFlg() {
        return psFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MACHINE_LIST.PS_FLG
     *
     * @param psFlg the value for M_MACHINE_LIST.PS_FLG
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public void setPsFlg(String psFlg) {
        this.psFlg = psFlg;
    }
}