package amilalaflower.mbg.entity;

public class MMachineKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MACHINE.MACHINE_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    private Integer machineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MACHINE.MACHINE_ID
     *
     * @return the value of M_MACHINE.MACHINE_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MACHINE.MACHINE_ID
     *
     * @param machineId the value for M_MACHINE.MACHINE_ID
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }
}