package amilalaflower.mbg.entity;

public class MMachine extends MMachineKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MACHINE.MACHINE_NAME
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    private String machineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MACHINE.MACHINE_NAME
     *
     * @return the value of M_MACHINE.MACHINE_NAME
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MACHINE.MACHINE_NAME
     *
     * @param machineName the value for M_MACHINE.MACHINE_NAME
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
}