package amilalaflower.mbg.entity;

public class WMachineDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.W_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Nov 13 19:35:58 JST 2016
     */
    private Integer dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.W_MACHINE_DATA.DATA_ID
     *
     * @return the value of dbo.W_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Nov 13 19:35:58 JST 2016
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.W_MACHINE_DATA.DATA_ID
     *
     * @param dataId the value for dbo.W_MACHINE_DATA.DATA_ID
     *
     * @mbggenerated Sun Nov 13 19:35:58 JST 2016
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }
}