package amilalaflower.mbg.mapper;

import amilalaflower.mbg.entity.MMachine;
import amilalaflower.mbg.entity.MMachineExample;
import amilalaflower.mbg.entity.MMachineKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int countByExample(MMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int deleteByExample(MMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int deleteByPrimaryKey(MMachineKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int insert(MMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int insertSelective(MMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    List<MMachine> selectByExample(MMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    MMachine selectByPrimaryKey(MMachineKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByExampleSelective(@Param("record") MMachine record, @Param("example") MMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByExample(@Param("record") MMachine record, @Param("example") MMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByPrimaryKeySelective(MMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByPrimaryKey(MMachine record);
}