package amilalaflower.mbg.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import amilalaflower.mbg.entity.MMachineList;
import amilalaflower.mbg.entity.MMachineListExample;
import amilalaflower.mbg.entity.MMachineListKey;

public interface MMachineListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int countByExample(MMachineListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int deleteByExample(MMachineListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int deleteByPrimaryKey(MMachineListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int insert(MMachineList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int insertSelective(MMachineList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    List<MMachineList> selectByExample(MMachineListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    MMachineList selectByPrimaryKey(MMachineListKey key);

    List<MMachineList> selectTargetMachine(@Param("hallId") String hallId, @Param("acquisitionDate") Date acquisitionDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByExampleSelective(@Param("record") MMachineList record, @Param("example") MMachineListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByExample(@Param("record") MMachineList record, @Param("example") MMachineListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByPrimaryKeySelective(MMachineList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_MACHINE_LIST
     *
     * @mbggenerated Sun Nov 13 19:42:21 JST 2016
     */
    int updateByPrimaryKey(MMachineList record);
}